name: Deploy Angular App to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use a supported Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Angular application
      - name: Build Angular App
        run: npm run build -- --configuration=production

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_BEACH_045132B00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token
          action: "upload"
          app_location: "dist/coding-hub"  # Path to the built Angular app
          output_location: ""  # No API, so leave this empty
